"""date column added

Revision ID: 49a2569916c1
Revises: 
Create Date: 2022-01-25 17:56:13.627572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a2569916c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_entry_date', sa.DateTime))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_entry_date')
    # ### end Alembic commands ###
